## Tutorial 5

The bacteria genus _Acetobacter_ produces acetic acid by using ethanol as substrate. Most commercial vinegar (acetic acid) is produced via the **aerobic** conversion of ethanol.

<img src="vinegar.jpg" width="220" />

The metabolic pathway of the process is given by the following:

<img src="aceticmap.png" width="400" />

The following physiological parameters are known:

|$\alpha \qquad \qquad$|$\gamma \qquad \qquad $|$\mu \qquad$|$\theta\qquad$|$P/O$
|----|-|-|-|-|-
|$\frac{\text{cmol $CO_2$}}{\text{cmol X}}$|$\frac{\text{mol ATP}}{\text{cmol X}}$|$\frac{1}{\text{h}}$|$\frac{\text{mol ATP}}{\text{cmol X}\cdot \text{h}}$| $\frac{\text {mol ATP}}{\text {mol NADH} }$
|0.08|2.4|0.3|0|1.6

The biomass formula is given by $CH_{1.8}O_{0.5}N_{0.2}$



a) Determine the mass based yield of acetic acid on ethanol. [0.26 g/g]

b) Will the value in (a) change if the growth rate ($\mu$) was 0.4$\frac{1}{\text{h}}$? 

c) What is the rate of ethanol consumption in (a)? [0.406 $\frac{\text{cmol Et}}{\text{cmol X}\cdot \text{h}}$] 

d) What will happen to the bacterium under anaerobic conditions?

e) If the $\theta$ value becomes 0.15 $\frac{\text{mol ATP}}{\text{cmol X}\cdot \text{h}}$, what will the answer in (a) become and why? [0.413 g/g] 

f) What fraction of ATP is spent on maintenance in (e)? [17.2%]

g) What fraction of ethanol is spent on maintenance in (e)? [46.5%]  

h) What is the maximum mass based yield of acetic acid on ethanol and what will you do to achieve this? [1.28 g/g]




[Back to all tutorials](http://localhost:8888/notebooks/Dropbox/1_CBI%20310/2017/Tutorials/All%20tutorials.ipynb)

beta calc:

In [15]:
import numpy

S = numpy.matrix([[-1,1,1,0],
                  [-6,0,4.2,2],
                  [0,0,1,0],                  
                  [0,1,0,0]])  

S

matrix([[-1. ,  1. ,  1. ,  0. ],
        [-6. ,  0. ,  4.2,  2. ],
        [ 0. ,  0. ,  1. ,  0. ],
        [ 0. ,  1. ,  0. ,  0. ]])

In [16]:
alpha = 0.08

C = numpy.matrix([[0,0,1,alpha]]).T
Y = numpy.linalg.solve(S,C)

beta = Y[3]
beta 

matrix([[ 1.14]])

In [17]:
#a = float(Y[3])*0.844444

#print(a)

rate calc

In [20]:
import numpy

gamma = 2.4
mu = 0.3
PO = 1.6

S = numpy.matrix([[-1,1+alpha,1,0],
                  [0,beta,0.5,-2],
                  [0,-gamma,0.25,2*PO],                  
                  [0,1,0,0]])  

S

matrix([[-1.  ,  1.08,  1.  ,  0.  ],
        [ 0.  ,  1.14,  0.5 , -2.  ],
        [ 0.  , -2.4 ,  0.25,  3.2 ],
        [ 0.  ,  1.  ,  0.  ,  0.  ]])

In [21]:
C = numpy.matrix([[0,0,0,mu]]).T
Y = numpy.linalg.solve(S,C)
Y

matrix([[ 0.48857143],
        [ 0.3       ],
        [ 0.16457143],
        [ 0.21214286]])

In [14]:
#a = float(Y[3])*0.844444

#print(a)