## Tutorial 1
$$$$
<img src="succi1.jpg" width="750" />
$$$$
The rumen bacterium *Actinobacillus succinogenes* 

consumes glucose anaerobically to produce biomass, succinic and acetic acid when $NH_3$ is used as nitrogen source. Carbon dioxide can be a reagent or product in this reaction, while water is formed as product. 

You can assume the standard elemental composition for the biomass.

It was determined from a fermentation run that the acetic acid yield was 

0.19 $\frac{g \,AA}{g \, Gluc}$ and the biomass yield 0.0656 $\frac{g \,X}{g \, Gluc}$


a)	Determine the mass based yield of succinic acid on glucose. [0.816 $\frac{g}{g}$]
$$$$
b)	Is $CO_2$ formed as product or used as reagent? Determine the moles of $CO_2$ formed/used per cmol of glucose used. [0.1 mol/cmol]
$$$$
c) Repeat the calculation in (a) using the degree of reduction ($DOR$) method. 	
$$$$
d) What will be the mass based succinic acid yield on glucose if zero biomass formed? Acetic acid yield remains the same. [0.91 $\frac{g}{g}$]



# A

In [3]:
import numpy
S = numpy.matrix([[-1,0,1,1,1,1,0],
                  [-2,-3,1.8,1.5,2,0,2],
                  [-1,0,0.5,1,1,2,1],                  
                  [0,-1,0.2,0,0,0,0],
                  [1,0,0,0,0,0,0],
                  [0,0,1,0,0,0,0],
                  [0,0,0,0,1,0,0]])  

S



matrix([[-1. ,  0. ,  1. ,  1. ,  1. ,  1. ,  0. ],
        [-2. , -3. ,  1.8,  1.5,  2. ,  0. ,  2. ],
        [-1. ,  0. ,  0.5,  1. ,  1. ,  2. ,  1. ],
        [ 0. , -1. ,  0.2,  0. ,  0. ,  0. ,  0. ],
        [ 1. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
        [ 0. ,  0. ,  1. ,  0. ,  0. ,  0. ,  0. ],
        [ 0. ,  0. ,  0. ,  0. ,  1. ,  0. ,  0. ]])

In [4]:
C = numpy.matrix([[0,0,0,0,1,0.08,0.19]]).T
Y = numpy.linalg.solve(S,C)
Y

matrix([[ 1.        ],
        [ 0.016     ],
        [ 0.08      ],
        [ 0.82971429],
        [ 0.19      ],
        [-0.09971429],
        [ 0.13971429]])

since r6 is negative it is actually a reagent


In [5]:
import numpy
S = numpy.matrix([[-1,0,1,1,1,-1,0],
                  [-2,-3,1.8,1.5,2,0,2],
                  [-1,0,0.5,1,1,-2,1],                  
                  [0,-1,0.2,0,0,0,0],
                  [1,0,0,0,0,0,0],
                  [0,0,1,0,0,0,0],
                  [0,0,0,0,1,0,0]])  

S

matrix([[-1. ,  0. ,  1. ,  1. ,  1. , -1. ,  0. ],
        [-2. , -3. ,  1.8,  1.5,  2. ,  0. ,  2. ],
        [-1. ,  0. ,  0.5,  1. ,  1. , -2. ,  1. ],
        [ 0. , -1. ,  0.2,  0. ,  0. ,  0. ,  0. ],
        [ 1. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
        [ 0. ,  0. ,  1. ,  0. ,  0. ,  0. ,  0. ],
        [ 0. ,  0. ,  0. ,  0. ,  1. ,  0. ,  0. ]])

In [6]:
C = numpy.matrix([[0,0,0,0,1,0.08,0.19]]).T
Y = numpy.linalg.solve(S,C)
Y

matrix([[ 1.        ],
        [ 0.016     ],
        [ 0.08      ],
        [ 0.82971429],
        [ 0.19      ],
        [ 0.09971429],
        [ 0.13971429]])

In [7]:
Y[3]

matrix([[ 0.82971429]])

In [9]:
a = (Y[3]*118*6)/(4*180)

a

matrix([[ 0.81588571]])

# B:

Reagent

In [11]:
Y[5]

matrix([[ 0.09971429]])

# C:

In [21]:
import numpy
S = numpy.matrix([[-1,0,1,1,1,-1],
                  [-4,0,4.2,3.5,4,0],                  
                  [0,-1,0.2,0,0,0],
                  [1,0,0,0,0,0],
                  [0,0,1,0,0,0],
                  [0,0,0,0,1,0]])  

S

matrix([[-1. ,  0. ,  1. ,  1. ,  1. , -1. ],
        [-4. ,  0. ,  4.2,  3.5,  4. ,  0. ],
        [ 0. , -1. ,  0.2,  0. ,  0. ,  0. ],
        [ 1. ,  0. ,  0. ,  0. ,  0. ,  0. ],
        [ 0. ,  0. ,  1. ,  0. ,  0. ,  0. ],
        [ 0. ,  0. ,  0. ,  0. ,  1. ,  0. ]])

Removed H and O balances and replaces with DOR balance

And removed H2O row

In [22]:
C = numpy.matrix([[0,0,0,1,0.08,0.19]]).T
Y = numpy.linalg.solve(S,C)
Y

matrix([[ 1.        ],
        [ 0.016     ],
        [ 0.08      ],
        [ 0.82971429],
        [ 0.19      ],
        [ 0.09971429]])

In [23]:
Y[3]

matrix([[ 0.82971429]])

In [24]:
c = (Y[3]*118*6)/(4*180)

c

matrix([[ 0.81588571]])

# D:

In [12]:
import numpy
S = numpy.matrix([[-1,0,1,1,1,-1,0],
                  [-2,-3,1.8,1.5,2,0,2],
                  [-1,0,0.5,1,1,-2,1],                  
                  [0,-1,0.2,0,0,0,0],
                  [1,0,0,0,0,0,0],
                  [0,0,1,0,0,0,0],
                  [0,0,0,0,1,0,0]])  

S

matrix([[-1. ,  0. ,  1. ,  1. ,  1. , -1. ,  0. ],
        [-2. , -3. ,  1.8,  1.5,  2. ,  0. ,  2. ],
        [-1. ,  0. ,  0.5,  1. ,  1. , -2. ,  1. ],
        [ 0. , -1. ,  0.2,  0. ,  0. ,  0. ,  0. ],
        [ 1. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
        [ 0. ,  0. ,  1. ,  0. ,  0. ,  0. ,  0. ],
        [ 0. ,  0. ,  0. ,  0. ,  1. ,  0. ,  0. ]])

In [14]:
C = numpy.matrix([[0,0,0,0,1,0,0.19]]).T
Y = numpy.linalg.solve(S,C)
Y


matrix([[  1.00000000e+00],
        [  3.70074342e-17],
        [  0.00000000e+00],
        [  9.25714286e-01],
        [  1.90000000e-01],
        [  1.15714286e-01],
        [  1.15714286e-01]])

In [15]:
d = (Y[3]*118*6)/(4*180)

d

matrix([[ 0.91028571]])