tut 6 excel check

In [36]:
import numpy

alpha,beta, theta = 0.1,0.055, 0.02
r1, r5 = 0.15, 0.12019872

S = numpy.matrix([[0.2,-0.2475,-0.2,1/3,-1,1],
                  [0.8,-0.88917,-1,0.311111,-0.13333,0.333333],
                  [-0.2,0.25025,0.2,-0.36667,1.1,-1.1],                  
                  [0.55,-2.71817,-0.88333,0.111111,2/3,10/3],
                  [0,0,0,0,0,1],
                  [0,1,0,0,0,0]])  

C = numpy.matrix([[0,0,0,0,r5,r1]]).T
Y = numpy.linalg.solve(S,C)

print(S)

[[ 0.2        -0.2475     -0.2         0.33333333 -1.          1.        ]
 [ 0.8        -0.88917    -1.          0.311111   -0.13333     0.333333  ]
 [-0.2         0.25025     0.2        -0.36667     1.1        -1.1       ]
 [ 0.55       -2.71817    -0.88333     0.111111    0.66666667  3.33333333]
 [ 0.          0.          0.          0.          0.          1.        ]
 [ 0.          1.          0.          0.          0.          0.        ]]


In [37]:
Y

matrix([[ 1.74921891],
        [ 0.15      ],
        [ 1.5840355 ],
        [ 1.10043591],
        [ 0.48292237],
        [ 0.12019872]])

In [38]:
import pandas, numpy
pandas.read_excel('Tut 6 matrix.xlsx')

0         1         2         3         4    5 (O2)
0  0.20 -0.247500 -0.200000  0.333333 -1.000000  1.000000
1  0.80 -0.889167 -1.000000  0.311111 -0.133333  0.333333
2 -0.20  0.250250  0.200000 -0.366667  1.100000 -1.100000
3  0.55 -2.718167 -0.883333  0.111111  0.666667  3.333333
4  0.00  0.000000  0.000000  0.000000  0.000000  1.000000
5  0.00  1.000000  0.000000  0.000000  0.000000  0.000000

In [39]:
M = numpy.matrix(pandas.read_excel('Tut 6 matrix.xlsx'))
print(numpy.round(M, 3))

[[ 0.2   -0.248 -0.2    0.333 -1.     1.   ]
 [ 0.8   -0.889 -1.     0.311 -0.133  0.333]
 [-0.2    0.25   0.2   -0.367  1.1   -1.1  ]
 [ 0.55  -2.718 -0.883  0.111  0.667  3.333]
 [ 0.     0.     0.     0.     0.     1.   ]
 [ 0.     1.     0.     0.     0.     0.   ]]


In [40]:

C = numpy.matrix([[0,0,0,theta,r5,r1]]).T
r = numpy.linalg.solve(M,C)
r 

matrix([[ 1.5096174 ],
        [ 0.15      ],
        [ 1.3446174 ],
        [ 0.92140776],
        [ 0.42320964],
        [ 0.12019872]])